### ISSUE TITLE
Problème de parsing CSV

### ISSUE THREAD

**Issue by duplau** [eig-2017/the-magical-csv-merge-machine#11]
J'ai un fichier (assemblé à la main) qui pose problème, j'ai réduit au minimum en le limitant à une seule colonne (fichier en attachement), l'encodage est de l'UTF-8 valide, mais le parsing du CSV semble planter.

```
/Users/duplau/Dev/EIG/the-magical-csv-merge-machine/merge_machine/normalizer.py:162: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  dtype=str)._engine.data.dialect.delimiter
Error tokenizing data. C error: Expected 3 fields in line 3, saw 4

Error tokenizing data. C error: Expected 3 fields in line 3, saw 4

INFO:werkzeug:127.0.0.1 - - [25/Aug/2017 11:57:23] "POST /api/normalize/upload/077b81904b3ab8f373aa7f7feeb1eef7 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/engineio/middleware.py", line 49, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/duplau/Dev/EIG/the-magical-csv-merge-machine/merge_machine/api.py", line 1330, in upload
    _, run_info = proj.upload_init_data(stream, file_name)
  File "/Users/duplau/Dev/EIG/the-magical-csv-merge-machine/merge_machine/normalizer.py", line 252, in upload_init_data
    self.mem_data, sep, encoding, columns = self.read_csv(file, chars_to_replace)
  File "/Users/duplau/Dev/EIG/the-magical-csv-merge-machine/merge_machine/normalizer.py", line 191, in read_csv
    + ' a csv with "," as separator with utf-8 encoding')
Exception: Separator and/or Encoding not detected. Try uploading a csv with "," as separator with utf-8 encoding


```

**Comment by duplau** [comment]
[hal_labels.txt](https://github.com/eig-2017/the-magical-csv-merge-machine/files/1251528/hal_labels.txt)

(J'ai mis une extension txt car github refuse les .csv, et comme de toute façon il n'y a qu'une colonne...)

**Comment by duplau** [comment]
C'est réglé, le fichier `hal_labels.csv` est bien parsé à présent
