### ISSUE TITLE
Erreur après page de création d'un projet de Link

### ISSUE THREAD

**Issue by duplau** [eig-2017/the-magical-csv-merge-machine#12]
(Je ne pense pas que ce soit lié aux fichiers que j'utilise : un fichier source monocolonne, et "grid.csv" comme référence).

Scénario : nouveau projet de link, j'indique le noms des 2 fichiers source/référence, mais quand je clique sur "étape suivante" j'aboutis à la première page "Projet de normalisation" et j'ai le log d'erreur ci-dessous.

```
Exception: Project with id 3f02e6ca7b837508c9acbfb15b3a9557 could not be loaded
[pid: 31534|app: 0|req: 5/31] 193.50.162.131 () {46 vars in 895 bytes} [Fri Aug 25 13:26:02 2017] POST /api/link/select_file/c70ccbb39e51f0a81fd42ab2f79d1cba => generated 0 bytes in 86 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./abstract_project.py", line 69, in __init__
    self.metadata = self.read_metadata()
  File "./abstract_project.py", line 168, in read_metadata
    assert metadata['project_id'] == self.project_id
KeyError: 'project_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/engineio/middleware.py", line 49, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 1412, in select_file
    project_id=params['project_id'])
  File "./linker.py", line 193, in add_selected_project
    proj = UserNormalizer(project_id)
  File "./normalizer.py", line 48, in __init__
    super().__init__(project_id, create_new, description, display_name=display_name)
  File "./abstract_data_project.py", line 59, in __init__
    display_name=display_name)
  File "./abstract_project.py", line 71, in __init__
    raise Exception('Project with id {0} could not be loaded'.format(project_id))
Exception: Project with id 3f02e6ca7b837508c9acbfb15b3a9557 could not be loaded
```

**Comment by duplau** [comment]
Pas reproduit cette erreur après avoir mis en ligne le code actuel ce matin, donc on va dire que c'est corrigé :)
