### ISSUE TITLE
Erreur à la création d'un projet

### ISSUE THREAD

**Issue by duplau** [eig-2017/the-magical-csv-merge-machine#13]
J'ai mis à jour le code (backend et frontend) sur notre serveur, et j'obtiens une erreur à la création du projet (en cliquant pour passer de la page de création à celle de détection des valeurs manquantes).

Erreur dans les logs du worker :
`
Traceback (most recent call last):
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/engineio/middleware.py", line 49, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 391, in get_last_written
    request.json.get('before_module'))
  File "./abstract_data_project.py", line 103, in get_last_written
    file_name = self.metadata['last_written']['file_name']
KeyError: 'last_written'
`

Erreur dans l'UI (visible dans le navigateur) :

> A PHP Error was encountered
> 
> Severity: Notice
> 
> Message: Undefined index:
> 
> Filename: libraries/Private_functions.php
> 
> Line Number: 74
> 
> Backtrace:
> 
> File: /var/www/magical_ui/application/libraries/Private_functions.php
> Line: 74
> Function: _error_handler
> 
> File: /var/www/magical_ui/application/controllers/Project.php
> Line: 291
> Function: is_completed_step
> 
> File: /var/www/magical_ui/application/controllers/Project.php
> Line: 351
> Function: is_done_step
> 
> File: /var/www/magical_ui/index.php
> Line: 315
> Function: require_once

**Comment by duplau** [comment]
En fait, le problème ne semble pas se reproduire. Peut-être un problème au lancement d'un des processus ? ...
