### ISSUE TITLE
error during indexing !

### ISSUE THREAD

**Issue by Leobouloc** [eig-2017/the-magical-csv-merge-machine#50]
```Traceback (most recent call last):
  File "/home/m75380/.local/lib/python3.5/site-packages/rq/worker.py", line 713, in perform_job
    rv = job.perform()
  File "/home/m75380/.local/lib/python3.5/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/home/m75380/.local/lib/python3.5/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/m75380/Documents/eig/the-magical-csv-merge-machine/merge_machine/api_queued_modules.py", line 273, in _create_es_index
    proj.create_index(file_path, columns_to_index, force)
  File "/home/m75380/Documents/eig/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 758, in create_index
    self.ic.create(es, self.index_name, body=json.dumps(index_settings))
  File "/home/m75380/.local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: create() got multiple values for argument 'body'
```

**Comment by Leobouloc** [comment]
closed by https://github.com/eig-2017/the-magical-csv-merge-machine/commit/66842e4dc95a985390c6fd2012cbafda97e6e364

**Comment by Leobouloc** [comment]
https://github.com/eig-2017/the-magical-csv-merge-machine/issues
